// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdZViTuD7p2UET0qomE19IjWSq1FhQsc',
    appId: '1:545539448865:android:dcc7e63f25ebb72d340360',
    messagingSenderId: '545539448865',
    projectId: 'collexa-hub-5f0d8',
    storageBucket: 'collexa-hub-5f0d8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPPCdIezHwUCIAFAgYgbeGLjHBAyGCRc',
    appId: '1:545539448865:web:c688891fd1dfbeff340360',
    messagingSenderId: '545539448865',
    projectId: 'collexa-hub-5f0d8',
    authDomain: 'collexa-hub-5f0d8.firebaseapp.com',
    storageBucket: 'collexa-hub-5f0d8.firebasestorage.app',
    measurementId: 'G-E20KXHYLL3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2KNvnRkhNlrLVyW7Qz2bGj4D1dysRQHQ',
    appId: '1:545539448865:ios:2c062c9b504f39b4340360',
    messagingSenderId: '545539448865',
    projectId: 'collexa-hub-5f0d8',
    storageBucket: 'collexa-hub-5f0d8.firebasestorage.app',
    iosBundleId: 'com.example.collexahub',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2KNvnRkhNlrLVyW7Qz2bGj4D1dysRQHQ',
    appId: '1:545539448865:ios:2c062c9b504f39b4340360',
    messagingSenderId: '545539448865',
    projectId: 'collexa-hub-5f0d8',
    storageBucket: 'collexa-hub-5f0d8.firebasestorage.app',
    iosBundleId: 'com.example.collexahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPPCdIezHwUCIAFAgYgbeGLjHBAyGCRc',
    appId: '1:545539448865:web:9f25b67c122fc27c340360',
    messagingSenderId: '545539448865',
    projectId: 'collexa-hub-5f0d8',
    authDomain: 'collexa-hub-5f0d8.firebaseapp.com',
    storageBucket: 'collexa-hub-5f0d8.firebasestorage.app',
    measurementId: 'G-QZDCWPD0TC',
  );

}